### ISSUE TITLE
Add renderRoot in host (LitElement)

### ISSUE THREAD

**Issue by evilz** [fable-compiler/Fable.Lit#22]
Hello,

I think we should had `renderRoot` in type `LitElement`. 

I try to do something like this

```
let input () : HTMLInputElement =
        host?renderRoot?querySelector ("#newitem")
```

Maybe I miss something with  `host.el` ???
when I change `useShadowDom` to false this is working.

What do you think ?

**Comment by AngelMunoz** [comment]
I can confirm that 
[Lit supports this by default in this sample repl](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBodG1sLCBMaXRFbGVtZW50IH0gZnJvbSAnbGl0JztcblxuY2xhc3MgU2FtcGxlRWwgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiBcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYDxidXR0b24gQGNsaWNrPSR7KCkgPT4gY29uc29sZS5sb2codGhpcy5yZW5kZXJSb290KX0-Y29uc29sZSByZW5kZXIgcm9vdDwvYnV0dG9uPmBcbiAgfVxufVxuXG5jbGFzcyBTYW1wbGVFbDIgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgXG4gIFxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPGJ1dHRvbiBAY2xpY2s9JHsoKSA9PiBjb25zb2xlLmxvZyh0aGlzLnJlbmRlclJvb3QpfT5jb25zb2xlIHJlbmRlciByb290PC9idXR0b24-YFxuICB9XG4gIFxuICBjcmVhdGVSZW5kZXJSb290KCkge1xuICAgIHJldHVybiB0aGlzO1xuICB9XG59XG5cbndpbmRvdy5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3NhbXBsZS1lbCcsIFNhbXBsZUVsKTtcbndpbmRvdy5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3NhbXBsZS1lbDInLCBTYW1wbGVFbDIpO1xuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzYW1wbGUtZWw-PC9zYW1wbGUtZWw-IDxzYW1wbGUtZWwyPjwvc2FtcGxlLWVsMj5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

but can you share a more complete example of what you were trying to do? a simple component definition perhaps

**Comment by alfonsogarciacaro** [comment]
Thanks for pointing this @evilz! You're definitely right. I was using `.el` as a "fake" property to access the HTMLElement because it was not easy to make LitElement inherit from it (right now, HTMLElement is defined as a interface in Fable.Browser.Dom), but `renderRoot` is a much better choice because it matches Lit documentation and it also gives you directly the shadowRoot when present. I've changed it :+1:
