### ISSUE TITLE
How to import FluentUI web components

### ISSUE THREAD

**Issue by JordanMarr** [fable-compiler/Fable.Lit#30]
Greetings!

I'm trying out Fable.Lit and trying to import and register the FluentUI web components, but I'm not sure how to do it.

I tried `JsInterop.importAll "@fluentui/web-components"`, but according to the [install guide](https://docs.microsoft.com/en-us/fluent-ui/web-components/getting-started/install-packages) it looks like I need to call:
```js
import { allComponents, provideFluentDesignSystem } from '@fluentui/web-components';
provideFluentDesignSystem().register(allComponents);
```

So I guess I need to create some minimal custom bindings to accomplish this?

**Comment by AngelMunoz** [comment]
Yes, the second part, fluentui/fast-design components have additional setups in javascript (like the one you found in the docs)

because the way they open their design system to be customizable

I'll try to get you a sample

**Comment by JordanMarr** [comment]
Yesss! I was hoping you would intercept my distress call! 😄

**Comment by AngelMunoz** [comment]
```fsharp
let allComponents: obj = importMember "@fluentui/web-components"
let provideFluentDesignSystem: unit -> obj = importMember "@fluentui/web-components"

provideFluentDesignSystem()?register(allComponents)
```

Slightly hacky but it works of course you can choose do all of that on the JS side (because there's a bunch of JS to configure properly fluent components) or in the fable side with bindings as you go
![image](https://user-images.githubusercontent.com/8684875/167963838-31c6ff01-b32c-4080-b6a7-406184ae0a44.png)

Sample here https://github.com/AngelMunoz/FluentSample

**Comment by JordanMarr** [comment]
Awesome! Thanks!

**Comment by JordanMarr** [comment]
One other question (not specific to Lit but to FluentUI):
I noticed that none of the FluentUI web component controls have any events in the docs. 
Take the [fluent-number-field](https://docs.microsoft.com/en-us/fluent-ui/web-components/components/number-field) for example: it has a `value` property, but no `onchange` that I can see.

[Searching](https://github.com/microsoft/fluentui/search?q=fluent-number-field) through the repo, I can't find any custom events.

Am I missing some integral concept about how to work with web components?

**Comment by AngelMunoz** [comment]
That goes a small rabbit hole, all of the fluent-ui elements are composed from fast-element which defines `$emit(... options ...)` https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/src/components/fast-element.ts#L26-L30

So ideally if you want to know more about fluent-ui elements you can always fall back to the FAST design counterpart https://www.fast.design/docs/category/components and https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/src where most of the components are defined (and likely where you can find the correct events/properties)

examples 
- https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/src/accordion#events-1
- https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/src/tabs#events
- https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/src/number-field#events

**Comment by JordanMarr** [comment]
Nice sleuthing! Sure enough, it works:

```js
let count, setCount  = Hook.useState 50
<div>{count}</div>
<fluent-number-field
    @change={fun _ -> printfn "changed"}
    value={count}
    step={10}>
</fluent-number-field>
```
