### ISSUE TITLE
Incongruence in documentation

### ISSUE THREAD

**Issue by francotiveron** [fable-compiler/Fable.Lit#55]
the namespace/module **Lit.Elmish.HMR** shown in this [example](https://fable.io/Fable.Lit/docs/templates.html#elmish) doesn't seem to exist

```
open Elmish
open Lit

type Model = ..
type Msg = ..

let init() = ..
let update msg model = ..
let view model dispatch = ..

open Lit.Elmish
open Lit.Elmish.HMR

Program.mkProgram initialState update view
|> Program.withLit "app-container"
|> Program.run
```

**Comment by alfonsogarciacaro** [comment]
Thanks for catching this @francotiveron! I think we made Elmish.HMR compatible with Lit after writing that sample so you're right there should be no need for the `Lit.Elmish.HMR` namespace. I've removed the line 👍
