### ISSUE TITLE
Update to .net 6

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/Fable.Lit#67]
Please Consider updating to .net 6 or 7.

**Comment by alfonsogarciacaro** [comment]
I don't have an objection, but it's there a difference in your app if the library targets netstandard or net 6? If I'm not mistaken you can target net 6 and use the new APIs (as long as they're supported by Fable) and still use libraries targeting netstandard.

**Comment by OnurGumus** [comment]
I think, no difference, just ergonomics and convenience :) .NET 6 is the latest stable and whoever tries the sample will error out if .NET 5 is not installed. Just gives the sense of project is well maintained

**Comment by alfonsogarciacaro** [comment]
If I'm not mistaken all projects in this repo (even the sample) target netstandard2.0, did you get an error because net5 was not installed in your machine?

**Comment by OnurGumus** [comment]
Yes you are right sticking to .net 2.0 is a good practice. But your global.json points to .net 5 , and hence the error :). I guess I should have stated clearly in the first post.
https://github.com/fable-compiler/Fable.Lit/blob/main/global.json

**Comment by alfonsogarciacaro** [comment]
Ah, ok! Got it, sorry, I was confused at first 😅 Yes, it makes total sense to update global.json. I'll do it! 👍
