### ISSUE TITLE
Should Fable.Lit build to Typescript ?

### ISSUE THREAD

**Issue by goswinr** [fable-compiler/Fable.Lit#80]
I am using fable in a much larger TS and Angular project at work. I would like to compile all my F# to TS only. But the emitted TS from Fable.Lit seems to be invalid.
How could I fix this TS error on the F# side? 
![image](https://github.com/user-attachments/assets/5cc03259-0b28-469a-b7af-699fe4c39a41)
but LitElementUtil_PropConfig seems to have the required members:
![image](https://github.com/user-attachments/assets/3d24a858-48f0-48a5-ae70-1388f9ba451d)

I update fable to 4.20, all nuget and npm dependencies and added TS here:
https://github.com/goswinr/Fable.Lit/tree/2024
after a root `npm i`  run  `dotnet fable --lang ts` in `/src/lit`

**Comment by goswinr** [comment]
Closing here, I opened an issue on fable compiler: https://github.com/fable-compiler/Fable/issues/3891

**Comment by MangelMaxime** [comment]
Yes, Fable compilation TypeScript is not as robust as the one for JavaScript because there are less users targeting it.

If you find bug with the TypeScript generation, opening an issue on Fable repo is the way to go and we will try to fix it :)
